# EVM Track Configuration (TOML format)
rpcurl = "https://rpc.ankr.com/eth"
max-requests-per-second = 15
event_sigs_path = "./data/event_sigs.json"
func_sigs_path = "./data/func_sigs.json"

[actions.transfer]
enabled = true
options = { min_amount = "500000000000000000" }

  [actions.transfer.addresses]
  "0xA0b86a33E6418de4bE4C96D4c3c1EbcDFf0aA78E" = {}
  "0xdAC17F958D2ee523a2206206994597C13D831ec7" = {}

[actions.deployment]
enabled = true
addresses = {}
options = {}

[actions.Logging]
enabled = true
addresses = {}

  [actions.Logging.options]
  log-events = true
  log-transactions = true
  log-blocks = false
  enable-terminal-logs = true
  enable-discord-logs = false
